ProductAssormentServices/Controllers/AssortmentController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProductAssortmentServices.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ProductAssortmentServices.Service;
using System.Text;

namespace ProductAssortmentServices.Controllers
{
    public class AssortmentController : Controller
    {
        // Get All Assortment List
        public async Task<IActionResult> Assortment()
        {
            List<Assortments> assortmentList = new List<Assortments>();
            
            string apiResponse = await Helper.GetAssortments(); // Call Api 
            assortmentList = JsonConvert.DeserializeObject<List<Assortments>>(apiResponse);
            return View(assortmentList);
        }

        // Get Assortment  by Assortment Id
        public ViewResult GetAssortments() => View();
        [HttpPost]
        public async Task<IActionResult> GetAssortments(int id)
        {
            Assortments assortment = new Assortments();

            List<string> getResponse = await Helper.GetAssortmentByID(id); // Call Api
            string statusCode = getResponse[0];
            string apiResponse = getResponse[1];
            
            assortment = JsonConvert.DeserializeObject<Assortments>(apiResponse);
            if (statusCode != "200")
            {
                ViewBag.Message = "Something Wrong.Try again";
            }
            return View(assortment);
        }

        // Add Assortment
        public ViewResult AddAssortments() => View();
        [HttpPost]
        public async Task<IActionResult> AddAssortments(Assortments assortment)
        {
            Assortments receivedAssortments = new Assortments();
           
             
            List<string> getResponse = await Helper.AddAssortment(assortment); // Call Api
            string statusCode = getResponse[0];
            string apiResponse = getResponse[1];

            receivedAssortments = JsonConvert.DeserializeObject<Assortments>(apiResponse);
            if (statusCode == "201")
            {

                ViewBag.Message = "Save !!";
            }
            else
            {
                ViewBag.Message = "Not Save";
            }
            return View(receivedAssortments);
        }
    }
}

ProductAssormentServices/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http;
using ProductAssortmentServices.Models;
using Newtonsoft.Json;
using ProductAssortmentServices.Service;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace ProductAssortmentServices.Controllers
{
    public class ProductController : Controller
    {
       // Get All Products List
        public async Task<IActionResult> Product()
        {
            List<Products> productList = new List<Products>();
            string apiResponse = await Helper.GetProduct(); // Call Api
            productList = JsonConvert.DeserializeObject<List<Products>>(apiResponse);
            return View(productList);
        }

        // Get Product by Product id
        public ViewResult GetProducts() => View();
        [HttpPost]
        public async Task<IActionResult> GetProducts(int id)
        {
            Products products = new Products();
            
            
            List<string> getResponse = await Helper.GetProductByID(id); // Call Api
            string statusCode = getResponse[0];
            string apiResponse = getResponse[1];
            products = JsonConvert.DeserializeObject<Products>(apiResponse);
            if (statusCode != "200")
            {
                ViewBag.Message = "Something Wrong.Try again";
            }
            return View(products);
        }

        // Add Assortment 
        public ViewResult AddProducts() => View();
        [HttpPost]
        public async Task<IActionResult> AddProducts(Products products)
        {
            Products receivedProducts = new Products();

            List<string> getResponse = await Helper.AddProduct(products); //Call Api
            string statusCode = getResponse[0];
            string apiResponse = getResponse[1];
       
            receivedProducts = JsonConvert.DeserializeObject<Products>(apiResponse);
            if (statusCode == "201")
            {
               
                 ViewBag.Message = "Save !!" ;
                    
            }
            else
            {
                ViewBag.Message = "Not Save";
            }
            return View(receivedProducts);
        }

    }
}

ProductAssormentServices/Controllers/ProductToAssortmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ProductAssortmentServices.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;
using ProductAssortmentServices.Service;
using Newtonsoft.Json;
using System.Text;
using Newtonsoft.Json.Linq;
using RestSharp;

namespace ProductAssortmentServices.Controllers
{
    public class ProductToAssortmentController : Controller
    {
        
        // Get Assortment Data and Product Date for Add to AssortmentProduct
        public async Task<IActionResult> ProductToAssortment()
        {
            Assortments assrt = new Assortments();
            assrt.AssortmentDropDownList = await Utils.PopulateDropDownAssortment(); // Api call for get Assortments Data
            assrt.ProductList= await Utils.PopulateDropDownProduct();  // Api call for get Products Data
            return View(assrt);
        }

        // Add Assorment and Product to AssortmentProdcuts.
        [HttpPost]
        public async Task<IActionResult> ProductToAssortment(Assortments assrt)
        {
            string statusCode;
            Assortments receivedAssortments = new Assortments();
            List <string> getResponse= await Helper.AddAssortmentProducts(assrt);
            statusCode = getResponse[0];
            string getApiResponse = getResponse[1];
            
            receivedAssortments = JsonConvert.DeserializeObject<Assortments>(getApiResponse);
            assrt.AssortmentDropDownList = await Utils.PopulateDropDownAssortment();
            assrt.ProductList = await Utils.PopulateDropDownProduct();

            if ( statusCode=="201")  // Check response
            {
                var selectedItem = assrt.AssortmentDropDownList.Find(p => p.Value == assrt.AssrtmntId.ToString());
                var selectedItemProduct = assrt.ProductList.Find(p => p.Value == assrt.ProductId.ToString());
                if (selectedItemProduct != null)
                {
                    selectedItem.Selected = true;
                    selectedItemProduct.Selected = true;
                    ViewBag.Message = "Save !!" + "||Assortment ID: " + selectedItem.Value + "," + selectedItem.Text;
                    ViewBag.Message += "|| Product ID:" + selectedItemProduct.Value + "," + selectedItemProduct.Text;
                }
            }
            else
            {
                ViewBag.Message = "Not Save";
            }

            return View(assrt);
        }
    }
}

ProductAssormentServices/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Product And Assortment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="HomeIndex">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Product">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assortment" asp-action="Assortment">Assortment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductToAssortment" asp-action="ProductToAssortment">Product To Assortment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProductAssormentServices/Views/Shared/_ProductDropDown.cshtml
@model Assortments
@{ Layout = null; ViewBag.Title = "Product to Assortment Product drop down";}


<select asp-for="ProductId">
    <option value="-1">Select Product</option>
    @foreach (var item in Model.ProductList)
    {
        <option value="@item.Value">@item.Text</option>
    }
</select>